apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 69.7.1
    helm:
      values: |
        prometheusOperator:
          crds:
            enabled: true
        grafana:
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - grafana.home.romangzz.com
            annotations:
              traefik.ingress.kubernetes.io/router.middlewares: auth-authelia-forwardauth@kubernetescrd
          additionalDataSources:
            - name: Loki
              type: loki
              access: proxy
              url: http://loki.monitoring.svc.cluster.local:3100
              version: 1

        prometheus:
          prometheusSpec:
            podMonitorSelectorNilUsesHelixValues: false
            serviceMonitorSelectorNilUsesHelixValues: false
            ruleSelectorNilUsesHelixValues: false
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: local-path
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 10Gi
        
        nodeExporter:
          extraArgs:
            - --collector.hwmon
          hostRootfs: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - FailOnSharedResource=false