---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: recyclarr-config
  namespace: media
spec:
  encryptedData:
    recyclarr.yml: AgAVNqS5Y3kmcgIxPNIQxSd2M1CWamhmcOZB2VadCTqQoAbZHOL+6/JvcEkevL/DKuGs28ZxJNDUSRmXxVWFLKzhSbRyk43MR4jhAC9T6fN/6Qz9U3lhO4Y9YTif9Y7iBPclF57voxGPRjpZjgUsKaOEK+oGKnmr4o6Y74sStwpszsp+DzuuZ+0Vpl/UcORByEVTG1Bp+cVHOt922gfaSCdToZ4nrIjDFMyFS8a6x/nDCjDrMIfO52fjCFjbToFIIn5lGhFfj9zWZcxOLnoNrTwAIA5EVRdhs+nK+3NyPkdq6LwwKQ2vLMT7AVVBY3VRouA2Ob0hhlC+tS/jv5ococJ6ZwaN0RpYWVku3qAmPceBJkKUO1ta/FAvn2gPuK6kVDK/9EWkBFyI0gklCJO8d236zNg6DA66C4LLwca/XNhbazFqu2c8IkI3iuXUKtWbtfVvHQCRY00etNlfvLzThcILlmFqVkaelFcz4DvbnvKAl+JMdDjlsYx1toG2Ugh13kXJN70uPOB734gRdjeLe47g2r7zvIXMpla/SRosTkTAC3KWc9S4gu97vpBCNQMrvYDQrpKnKJO0aMM3Kp+4xMcJh+RQ/PIqe0Xr9c4I18MHwsiqPuGrWnZxIayQMXPuEbkFiZGYnHwZN+Rpa/hmloRy18nk+I7JBzpwxWGFyDm+cSx6zOofMon3NoBXq8NTdnlixK6UfA2VaZt3q5f8c6VL4OcALdsTTQGcz9GgjEsFcDI9NTeARzKtF2laAGv8sbMl9NymgWWcQpq02GcITlnsXYW1dRKVm9lM85m8jSL9+ZGs6ZI7y2hu5R/0fQVZ4npiyWuIJsQFvBqSanVBk8K8/yyB+pWCCZuX8vUb1wzC7JW6obL1QD/dS93pqfNZ/L6CRFzrYhK+PNO0G1oQrl7mgAw/zZ9m3Oid0oORrBHUu1XAtUivc7a+9KBA0dRGznUUUL+4+DvgvwOI79+bHcgFZk6kuhxB0RuGskxfmvCGWwXesdzElNg6Rnqt8EtWt9d4F9VKnz5YFC9pJk6WVeX2YoRmLNY8eWe1TJ72XnkKcwmiOu5BJ5fnsHN5ea9bMuV90G/TxoRGIPwAFYMLzsRtylU7O6oSSBW+fw+1cefD3cZgqpqUnLFmeMdPROQJIRGcf5QDb3AZYSpcYW6a+eGdvS0K2BA+b9YVPBCfX/rtRzRk/g8Hj7n4KNpBX/vK4IEzRPrddKKZy+Vo0VjCKdU0a7xRa4MPDCUVWe/5s92OqJY4SAkUo6gHEWo2hKrWYLcUTsW6SeGWfqA1u+NIj7qeMl6KH59GgMjmSO7cDHFiVx2z7Bp4Mh3B1fDsYoCYMmVg/ZCdYgxCfX3QH3EPQnkx3c2xEgcLjZs9MBjoCRwCXx2VAK6/Vh4plO4rBnm16gUPWnct47xwhUiMVB16kugWnW3ZZiWEvvMB69a1i1liKN4oLiX3jqyQGwTXbMGjZnvdQ7xEXo2QvjseNDl2clX6hdBDiLTZr4O8XVOHQbALlLoD6ipN9DB5xQ97/HlJb/c=
  template:
    metadata:
      name: recyclarr-config
      namespace: media
    type: Opaque
