apiVersion: v1
kind: ResourceQuota
metadata:
  name: media-quota
  namespace: media
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 14Gi
    limits.cpu: "24"
    limits.memory: 28Gi
    requests.nvidia.com/gpu: "1"
    pods: "40"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: media-limits
  namespace: media
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 500m
        memory: 512Mi
