---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unpackerr-secret
  namespace: media
spec:
  encryptedData:
    RADARR_API_KEY: AgAkS8LqrWsv6RGSNn3PRhVY1l5BWLUkiH3N2C3+nm338e62bJtD55Nos6VUra0l492Pom0HrWWy2EXhieMTDEwXUd2B9BJOtmCtX31afXhLgwqJJfdnHfhVcibM8OrJ/PMLDAEjwxIHWIrU9H7H4kSBvroCzDmuogp7mKsjfvgG9G3rKmsuFf5c6yw1ogzc8kQ1/ZNqaYIxtr44/o3JQX8GFTQvE/ggCbAR5mgTHrni86HxhZ1cJgg8fYUSUyjlHgVFTaaqUZ+wK/BS38X7eIvL/erHkPN6wOP08hkcXr3ha8yJhYiPBn9lJo9fbjmZtB6RnWwIoV9AZLAXNCGV/kqEGenowh03BL9hALx6lGvqwVtuhelDrqf8Z6qgMkfaLqSWTJw0jpb9R7J695xrlLtQdLR66nFHtHHWc2gTZEKHkDV0W4H37BKJn3p91u3nE722JNFW5c8J/TqJJlkrgvdceFVsvq2iVHM87sIUklycUjOgZslLfTpsRC4PC0vTaFvRnEg9LKhK6q7JlNAnFxUyIuNQV9PQu49UmBzDXKLOdrlS4FF0/Ut1O+Im9CaT7uNDuUjN6hwJiAn0rwj2Zu1at91A8dh3Ef7jFJPenp0pTC+4Lil8DUtkmMt2jWWEPgWSLt8PqM9Pfozv/ocbYAO+WwJv20+56dbYyigZiibwFK7of8nkPgVy9g3w/zL9o14aGWE1jaoxXshdOY9njV0tRpXRWifpBjtsHqUZrf8iyA==
    SONARR_API_KEY: AgAhAFJA8T/fom4+UoKqBgAw2Ecb3ifL20YnfGor6ngAnR42dPjCftUh9D7drz86aJMYA9OVvR/alz7IpG95BXaRjVB2283yDmJEXC3Cn7HSsGvi0gEhgeKjw+MSF28w0RCXEkKJTDlkx5jUmRarTG+vo4bOvm/+PRddTmr2VoRPUnpbVjYVRXHlcRyGLBEwojJk2VRxp93iXHEa+kOCHv68RuShkHFNuTTu83LGwUXGAIHoBGKQmupW40BxLWIPAs5yFFL5LEMBdm0KaDieTtP52ySy5512dI0/b2sCsgsJ8Cu7Z7/z7n78RMMn5m3ApH7yx9KiCCjGogftBllyyfg/dQr5YhewxxrRA6HD8JCMrqp9pC/lZkYYUNVqDXv2NfVpQ9by+51emvKi7b5ikamsBZAArpSQGddEWF0kaLA5rExkN2j+xtw9sjrDGjofrVZdm9jb6EEc7TtBofSNk7yXnsbX5uzSLH/HlMEowMMq1P/qY+/6WKDm3mmVSHt3apQ+IimWGyXZ8d9Gc7/Qx9S0bnJdm4FH6uzp+pZ0NGfJ10pXO7/+eyz9ewymlwPm+JYvUYCTeufeXuavLGITtYPWCw3euElYBwzPyYOgDz4bJvBsbATNehpGT94nJtohKL8Rm8hYjTOb870CcmRQZbSt5LcZpF2ZOfiAB33H9uyjpSAzC4pRCyArrmX7oQVw+lmbd1k5KHH4ROR4HccCJ0rIC6xUfZCKHW6GNfCBrZFbuA==
  template:
    metadata:
      name: unpackerr-secret
      namespace: media
    type: Opaque
