---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unpackerr-secret
  namespace: media
spec:
  encryptedData:
    RADARR_API_KEY: AgAm/yinR6OKnL7SUhX2UUSbVgjoX6WZFdHWYFm3/VVBz2bDD9G3bY21P47XP02lO4tuoOFJtpkCfieHB/P+n5eDnDT897UfFbhk7ySEMrWImMMIH0vFJKd6X4BawTCxw68kICw9ms31J/p/YekTEZnYz5NzNH4uuS4Qn91yPgqKKzgnhmVdUjTPWqvUWtaLSCt3tcgqzIGSof/k/XhIHbAauaPtpdW8Jo+V+fKnzgKAtJnkhBrRhjU0JSzENORtK1AbNUY5Q3JaVAbr6MRkL4jLTFafUxroP5ddne5+HD9qKCEMn62XbHTB0KhOX3NasOyb+eGEsI72c+BZdFcwsS3dQbh1JXZfkqymyRPMM76qfIs1viDdfD3O6MO92HoxwcbsGjKaWIYhWfXyZJP8rBZ2BLkU0SdYbjbdYH5w3MxZ7pMheC+eQbT/xb+zco3sqbvvn62FQktUO3rbSLjpcJcXIzpf4iFmLCo+Ei9w82cMPh3k67ouwisYmBp00LURjHRGq0cWNEsMmYDxrtW2qc75q4/74R2K5rjiYv3PJjBtFj9ClTaZWtZZKBadlLUm3mI7fRQAu5Hb72LhjiQv74PIsZdGhaLh/eJhBGypvZyvAP+e5V1j9NpPpMKrAbbqDK/ze2QA688Y8n1GqpbMRqgZ2YX+ROup1Ai7q01kxgKBm9GYM7aZ+1Yyq0QUWuoFCsrjlKc4b0v+VZuMZ2jsmJoETUjjuC5HMEA8Z7GdEKllpA==
    SONARR_API_KEY: AgAWYSXxws3trnZrNrdkRprGJPNEMIDGhXjMdWwB8Ki0D3fh4CFeF7UbxXiB7eO2SnOWqKSCKUzhOCi3XlLG38KwFghuqCD+G6FfHUHMbv1bQTd5y/wOdT6NKDSqvi616svbcnk3uJkjtxp+dm375vrG+tI9y1eK4ykbr4Byo+uxMHAU2UF2lthEUBxQ94OX4KZreucx7Dl/REsYY0/lgtqhzo+696WZMgy6Xg8U3DyDVGbKgntW5OQAxnUmyPDryikBs9Bi+zPu+dzERrafhUSDm1Ae8yWdVC+rRkW4/k4wWpEmRGLlIgVSfgIR7tCv1YZl3O6sDWbP1oDIX6wx+syuWFWa+c7SZFuAd3CcLP+JwTIM3AiLuVJBHF52FkcyJkln7af28hry5n2xgnB1rHvrOrAfgZ9o7HXjttol4nWmqndQWq9VaV1v2BsRqzScVNiojaimHInZNCEQHIPpjKNBeO/KkLreA27F9/GhOmSCgKMTG6WowAY4us/OKrp1lbew9BmIrPIYdneyb1p4qbIp/Q1PeUSdv7biQ4J5fp38Ak895OdPZop0k3cZoAWPbnW1bD0C/+UyWQFQo3sYnFVrmE7wsA5VtQN334XiOVrnubXDaWJ2dTauz6/ssjSGXbCuafWImX7JMvhtxsgQZT3Q0kisI1a48FjK1tJoQ6LVh1WQajHAHw3vgDCC+UfbOgAFJytGNZlhJprZTmrP6N3Tn+vcdUP95oXLfcZn4flkVQ==
  template:
    metadata:
      name: unpackerr-secret
      namespace: media
    type: Opaque
