---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia-users
  namespace: auth
spec:
  encryptedData:
    users_database.yml: AgChmMMD2sQV9KaAKTiobO/jonDMDKATirqCS8Di6DxgXhUxgprcRJ3VgxNSNHSeeV8d51rIA5oIbrpyBwTIDrBGWV8wguidQK2v3KlJIfYRf7u48vgNxgvUc3p4uWNyJpqX6HPQLMO6NwL3f7NfylvE2IA3fenn/fDMTSyA7CWgUUaWyIqMCSirRJfAOlhrJFTAknOAZlN4sEvR/JQbyOJqwIPqVpuoVNEywthojMtX2lQpOMPBhWqmMSB5KOLX0VdnzCYtNRPnOUd8hrPS/i4aZuh9Lk0VRqOS2Za2ZlFfnbRNbcZopBZseT/63BBqCKkV1Zh0T7XgjpWOmIbaq+jJwR+Cud9CJ4aCYhUWsWuFnS/ku15Z/Ahd0v/hpM6pxOBAF2m42Lv0DtxLlmM+i4mspkXa9JUFDXWqm2koOtaspeu5DTAWBmoqHO9JEP8MnddPP6FDKF2t3cIYFujokv9QLsZsASPalwq2UAMbrkzMvCmnH3Z7lgDiEZ1QQEAZMh4fSawHYyzwSwcMnPEXFDYZZXs7ypOucrzSoaWoN6/8Hp0UEjPMqxjKn2vkYKswzgXEUgZjkq1gnyZN9otKfztn7nSEdM3dZ+XN2F2HhL/W7s1kjuPfTdPKoBSIoG7imxcDHp4SoB5ml6bIfm5lqHesujcdON4+ypOCcjRmkwCex8lLsFfiO8GcsFeQJiV8lIvSFs37p4Gh3zOJ2P/lX0jnhzQ268sxRrwvy1A/L7oJwsWbFb201s+MEkjpHqlyDTugc64hzxYxqRo0jyyJp1PAci+DcbvfbfT1zctLKMgoiQDL3xdfiY6EZ173eUIqILBLgp5OgG3wvjgwlkTw6xUcjsKaKpwSI9T/MC9LNii/TqX++qIFLhWM57DnVxrFPajlD43iQoPJF+b7JktDufhJWq238K3FWJB8jFhm3Xs2Z4TRtAXMK/7jO3PhBSkYkUqatckyIlFmWVMV+7WuFSP/V8MxMN1nYP4gn1fxrVL8R4/oHsV80+oO9ln/gTLulQ==
  template:
    metadata:
      name: authelia-users
      namespace: auth
    type: Opaque
