apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-authelia-middleware.yaml
  - sealed-secrets.yaml
  - cert-manager.yaml
  - cert-manager-config.yaml
  - authelia.yaml
  - ollama.yaml
  - dashboard.yaml
  - nvidia.yaml
  - omada.yaml
  - argocd-ingress.yaml
  - open-webui.yaml
  - monitoring.yaml
  - hermes-agent.yaml
  - media.yaml
  - n8n.yaml
  - tailscale.yaml


