apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-suite
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/romangzz/homelab'
    targetRevision: main
    path: apps/monitoring
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true