apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui-interface
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/romangzz/homelab'
    targetRevision: main
    path: apps/open-webui
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true