---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-auth
  namespace: tailscale
spec:
  encryptedData:
    authkey: AgBbr3XuEm0CpH6+7bjE3gxIszzve/Ed3VMZcklTcenHPS+UP4m7+YWLVzmRN529ucZSgYxiGya6wsVYpFhErnTh6R8HihUMjPe3QzmlRGru1KvnitdVVkJj1I43o8R7QNTjS/17cfL6ddW0mzecJVdxOHaLr3b7HxT3hKQQR5ZYhp+Bnjh5Ky4aVI2s8HVFZ44fjVr5B+qF09oYVOWYepgm56hNwKwhZx35yniJxoXyPUOnwgSQMJih++XxowfdNmw0AkTze8RblodsZ2WPld0PMjYmh/GgI+1bY+PHW5wWXNxbNaqFjQFSsBEEy9kOIjLA2kvuKKgykv3Y8vYLlCwAfZh17s1FtqduaeMBghg5u/OXiU/5xoSq8G+UJkB3jzBiI2+x9sRvbg5ZZnmld7TUxGRFYG2BW3NCeox0m7I4OOFuKEbnzlhnGFT/8MnlmX5i8IihQ7buo5ZjLgVnhPTIsNt9BakmXjIvDlJzKAk3ZryNgGIZqoWsKOz1fVqEJp73VTWTrkowikmDDX7I0IMnbcKmf32g2iUoIl7P8N1F48sG9l6dssJgZn155Y65Gp5k3Ut9tehu421y7PMk/RQ/jYZ49lBt0IF+f4tFa+mzaVmJpSZlCp0vJuoR9ztSWhudeklX+BM4ObA8imxs45HzBm4q08lMcny/i4nQAAQAZ80VVRl8OEk9UU9gcpnfgyFsAZ8zyu+Ecvipeq0dU5NsfY6twZPEo4fLVT1h95S/QvUw/saHfIlpGoFNTiBHq17cEnrfIQr48NxROniVrA==
  template:
    metadata:
      name: tailscale-auth
      namespace: tailscale
    type: Opaque
