---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-auth
  namespace: tailscale
spec:
  encryptedData:
    authkey: AgBh0CdhSQsOmtVZzmLhm1GPpN1oqPjiOJ0M8TPmY9Rdcp0g2lM/YvvRWxARpnq5R1jkiGcqg0Ne64QJqkQzspeeCImbLNw6dRpzio0Jh6wAdXvbW89ajqIQX4PvTJPbw6SRTuEev67ywHqhQ67iXiRaA4acTrEpG0XYpDm4wyyJOMikIbCz3x/K5FZVVk1nmF6Aah0GGaFDxid2uAyZuiOxYTICEU6yarOkF+8B+cyAoUtgl6aJsQir0x5Rer1XufwoxdyRals+LZoL5wC24bzcjy82TWce0iYBO7DouotUAj3WH6/2lk7vICMBZY1JaGlfvLdGJPlh9+8IdXjHzOlmOvBwABLy4oLWnkNa0wVvboU1e3Ylwe9VojBcexM/oQaTFtQPwymUuD7wOsSFxE82rWIisaUfK4/kAwLtzKSRaepmcUF5KkxHqPQ08F9efWy+B3tXyOdYg8luNPg41IoNlPpSISzDX9VWZx28YuVKA4x4/GRUM0sFu399yA6Yt/p8nBSCXVlUxdY4SVd5vQTp6uLT7o7XpRNwlAFjRXnkTMqh8mz5+sxg1odrNVZA4k43ODpVa0rSsUlYGr4vF4vecHFc/F4+9qxNxbhYMzEHvegYmiacfDoMFDkmE2OsQ4f2/wnC29fmK2+VKHmWOlL6NVPxHmQlpU7HCbA5e9u+zV8Sc8DNeRjXpAou9AH1CoofXaNb7APyQMsdNDx8q6Y/OiqFr4DhW5MmNEXYtIAvCQjdqT5fCHjW36sznFMX0vaCx6K95RS59ubHX6cWRg==
  template:
    metadata:
      name: tailscale-auth
      namespace: tailscale
    type: Opaque
