apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-device-plugin-shared
  namespace: kube-system
data:
  sharing-config: |
    version: v1
    sharing:
      timeSlicing:
        resources:
        - name: nvidia.com/gpu
          replicas: 10
