---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-secret
  namespace: ai
spec:
  encryptedData:
    WEBUI_SECRET_KEY: AgCBXryamhfvWhsIvItFlTD++MMKJzijol6sb+CpyOD0d6l4a6ozKa31vy67VZgjTEVryYFev2xUuembkX1DiltkkWkT9zqBSnn2Vnx+r2RCph1Gb/vfmM8gHcNXRexaIV78Fn/Y8obmxoumwAf0dB6rCCHcuupsyHbbOD7gLQJOZqHz0gNvxtTihPeifB70W/e8EIZdrYSi8YYZlPp07gdnsmWF3DuNRSnHNZckoWQR+WH+s/c6jMugpvpb155ALXl5rLGs52tyn940rW7s+cSx1lVKNnNREfjrBkHkNdSD5Ef9YHbY36pIOyYif6rFfmWna7IlC84cAkhoN+Tnna4y8SUVpFjXhP/NYPklSsiHVPmjGLcNDTnI+wN3Y+Xo8/CvzDipUeLH+PEEzg+PLLzJ5BbAav4hYhKt9RO+iXhvSoDra0RTPM0hRw2DRLnyQarWGDRb4q1D7cL8bbB0xdzZI0wouFu9J5Ae0MmW4LZJJFBoSKg0Rj5YDYd/Wsdm5g6kDpXfjd6FirDWuf2g7PFyMDEQglWSvllJtxJF7OYA8NwLogjgY7YnNdqE+Xk5adrJa/hlYE/aIvEmZunzUrXh4h88++/WNC4Xn73xRPBmf3NoCEA4qyCgTiQZYOT9cG+MJh8fd2G+F1ONXpXA8DP0TJfIPm7Xu1qm4OiKU0SVZ7twXGUdql147uwGa6ukuxAqrMr2GOE5lJ4O4qbT/KJ5yzpHJMMh2v53CdgFbHxAH1GOUSopnktf
  template:
    metadata:
      name: open-webui-secret
      namespace: ai
    type: Opaque
