---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-secret
  namespace: ai
spec:
  encryptedData:
    WEBUI_SECRET_KEY: AgBV4AroMBbp8+GLVp5SFq8xFubTm67GofoW7dqz4zIlMZ14Qmna8La+x8Y5zLUgQxElodU1eE75Lujab5mcZLo1ZgcnbkK497zJSjRKS9Kj/8URvL2u7nt+ewqU8esYn3jLxMc2hTfsHFKwtocpV3pi+q05AM4eKbpX5H7fod9CUj9rI12o9WMxN1wtyIpjNHg34T7x+3sjps8HP5NC9Iw+qFYLBA2Oi5n5xafl5KY9EBHn22rLVlCGkxwPf8JGPRLosAj/0TNzVJPKVR99qcFEJhLnyoQ5a79zBMYpX6Oq8jutWSTyaDhLLhbggMCavQSZYx3Ly4Qq8HWjXBa1fi7PE2ngMeIbUkb9cO2cDa1BIrYn2IAlgjCQWOjtxx8hIVdvKAMc7zFoZOcUI/jX20ZxQEAwPCJ3cG2VKB53+oflvlkr9Dl/6k4ITNAvZXlToRLSM+0kaa7zw4H3dln0pNjZ5BBB7pkIT133CL8wofEPAtF8f8H7ui4vBJuFImHpLHD57GurTymhseMozBJgxiSXU7d6BDT0s83s5ZZye/dNEprZcQrcye9RnVyieGG2mO2Xja89x3rtYiuCUC3dxkeX/H2k/oZjvGQTM5M5QNeJq3t41BbezMhmgI2PX3bJhtL43mtulDZ4suTAzWZeU9bTKEe1g7Ui5oH2Lvj8x4iq58tY5ltaWXFpcj3IYFowOw40go4pffCjRg0JFpQMBnfoc5g8MU5y59ZNanvTx36O8WJx/qU=
  template:
    metadata:
      name: open-webui-secret
      namespace: ai
    type: Opaque
